controllers:
    resource: '@MetaFieldsBundle/Controller/'
    type: annotation
    prefix: '/{_locale}'
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

api_controllers:
    resource: '@MetaFieldsBundle/API/'
    type: annotation
    prefix: '/api'
